/* eslint-disable react-native/no-inline-styles */
import React from 'react';
import {StyleSheet, Platform, FlatList, Alert} from 'react-native';
import AsyncStorage from '@react-native-community/async-storage';
import {
  Text,
  Card,
  CardItem,
  Icon,
  Fab,
  Container,
  Picker,
  Left,
  Button,
} from 'native-base';
import {firebase} from '@react-native-firebase/analytics';
import {connect} from 'react-redux';
import {bindActionCreators} from 'redux';
import {ActionCreators} from '../actions';
import EventCard from '../components/EventCard/EventCard';
import Loading from '../components/Loading';
import MapView from '../components/Map/container';
import eventsSelector from '../selectors/events';
import userSelector from '../selectors/users';
import authenticationSelector from '../selectors/authentication';
import * as storageKeys from '../constants/storageKeys';

const styles = StyleSheet.create({
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainHeader: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 25,
  },
  mainHeaderAndroid: {},
  headerProfilePic: {
    width: 60,
    height: 60,
  },
});

class Home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      view: 'list',
    };
  }

  async componentDidMount() {
    if (this.props.sessionToken !== '' && this.props.sessionToken !== null) {
      this.props.getEvents();

      // Google Analytics
      // Shows when a user hits the home page
      Promise.all([
        firebase.analytics().setUserId(this.props.loggedInUserId),
        firebase.analytics().logEvent('home_page_view', {}),
      ]);

      let usernameDontAskAgain = null;
      try {
        usernameDontAskAgain = await AsyncStorage.getItem(
          storageKeys.USERNAME_DONT_ASK_AGAIN,
        );
      } catch (e) {}

      await this.props.getLoggedInUserInfo();
      console.log(usernameDontAskAgain, this.props.loggedInUsername);

      if (
        this.props.loggedInUsername.startsWith('user_') &&
        !!usernameDontAskAgain !== true
      ) {
        // Make sure the user doesn't have a auto-generated username
        Alert.alert(
          'We autogenerated your username. You can change it in Settings anytime.',
          this.props.loggedInUsername,
          [
            {
              text: "I'll do it later.",
              onPress: async () => {
                try {
                  await AsyncStorage.setItem(
                    storageKeys.USERNAME_DONT_ASK_AGAIN,
                    true,
                  );
                } catch (err) {}
              },
              style: 'destructive',
            },
            {
              text: 'Change now!',
              onPress: async () => {
                // Since it's on mount do ask again regardless.
                // try moving to app load?
                try {
                  await AsyncStorage.setItem(
                    storageKeys.USERNAME_DONT_ASK_AGAIN,
                    true,
                  );
                } catch (err) {}
                this.props.navigation.navigate('Profile');
                this.props.openEditUserInfoModal();
              },
            },
          ],
          {cancelable: false},
        );
      }
    }
  }

  getBannerUnitId() {
    if (__DEV__) {
      return 'ca-app-pub-3940256099942544/6300978111';
    } else if (Platform.OS === 'android') {
      return 'ca-app-pub-9804482407199604/7027103890';
    }
    return 'ca-app-pub-9804482407199604/4029760684';
  }

  getListView() {
    if (this.props.eventList === null) {
      return <Loading message="Loading latest updates... Please wait." />;
    } else if (this.props.eventList.length > 0) {
      return (
        <Container>
          <FlatList
            data={this.props.eventList.sort(function(a, b) {
              // Turn your strings into dates, and then subtract them
              // to get a value that is either negative, positive, or zero.
              return new Date(a.startDatetime) - new Date(b.startDatetime);
            })}
            onRefresh={() => {
              this.props.getEvents(true);
            }}
            refreshing={this.props.fetchingNew}
            renderItem={({item}) => {
              const isCreator = item.userId === this.props.loggedInUserId;
              return (
                <EventCard
                  isCreator={isCreator}
                  item={item}
                  deleteEvent={this.props.deleteEvent}
                  navigation={this.props.navigation}
                  showProfilePreviewModal={this.props.showProfilePreviewModal}
                />
              );
            }}
            keyExtractor={item => item.eventId}
          />
        </Container>
      );
    }
    return (
      <Card transparent style={styles.center}>
        <CardItem transparent>
          <Text>
            Nothing to show. Try adjusting your filter or create a new post.
          </Text>
        </CardItem>
      </Card>
    );
  }

  getMapView() {
    return <MapView />;
  }

  render() {
    return (
      <React.Fragment>
        <Container>
          <Container>
            <Card
              transparent
              style={
                Platform.OS === 'ios'
                  ? styles.mainHeader
                  : styles.mainHeaderAndroid
              }>
              <CardItem transparent>
                <Left>
                  <Button
                    transparent
                    dark
                    onPress={() => {
                      const view = this.state.view;
                      if (view === 'list') {
                        this.setState({
                          view: 'map',
                        });
                      } else {
                        this.setState({
                          view: 'list',
                        });
                      }
                    }}>
                    <Text style={{fontSize: 18}}>
                      {this.state.view === 'list' ? 'Map' : 'List'}
                    </Text>
                  </Button>
                </Left>
                <Picker
                  mode="dropdown"
                  iosHeader="Filter"
                  placeholder="Filter"
                  iosIcon={<Icon name="md-funnel" dark />}
                  style={{width: undefined, color: 'grey'}}
                  selectedValue={this.props.eventsFilter || 'upcoming'}
                  onValueChange={filter => {
                    this.props.changeEventsFilter(filter);
                  }}>
                  <Picker.Item label="Happening Now" value="upcoming" />
                  <Picker.Item label="Past" value="past" />
                  <Picker.Item label="Created By Me" value="created" />
                  <Picker.Item label="Joined By Me" value="joined" />
                </Picker>
              </CardItem>
            </Card>
            {this.state.view === 'list'
              ? this.getListView()
              : this.getMapView()}
          </Container>
          <Fab
            active={false}
            containerStyle={{}}
            style={{backgroundColor: '#990000'}}
            position="bottomRight"
            onPress={() => {
              this.props.navigation.navigate('CreateEvent');
            }}>
            <Icon name="add" />
          </Fab>
        </Container>
      </React.Fragment>
    );
  }
}

function mapDispatchToProps(dispatch) {
  return bindActionCreators(ActionCreators, dispatch);
}

function mapStateToProps(state) {
  return {
    sessionToken: authenticationSelector(state).sessionToken,
    eventList: eventsSelector(state).eventList,
    fetchingNew: eventsSelector(state).fetchingNew,
    sliderIndex: eventsSelector(state).sliderIndex,
    eventsFilter: eventsSelector(state).eventsFilter,
    loggedInUserId: userSelector(state).loggedInUserId,
    loggedInUsername: userSelector(state).loggedInUsername,
    loggedInDisplayName: userSelector(state).loggedInDisplayName,
    loggedInProfilePic: userSelector(state).loggedInProfilePic,
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps,
)(Home);
