// TABS
export const SET_ACTIVE_TAB_INDEX = 'SET_ACTIVE_TAB_INDEX';

// FORMS
export const INPUT_CHANGE = 'INPUT_CHANGE';
export const RESET_EVENT_FORM = 'RESET_EVENT_FORM';
export const RESET_APPFEEDBACK_FORM = 'RESET_APPFEEDBACK_FORM';

// SPINNER
export const SHOW_SPINNER = 'SHOW_SPINNER';
export const HIDE_SPINNER = 'HIDE_SPINNER';

// AUTHENTICATION
export const INVALID_SESSION = 'INVALID_SESSION';
export const CLEARED_INVALID_SESSION = 'CLEARED_INVALID_SESSION';
export const GET_SESSION_TOKEN_FROM_LOCAL_STORAGE = 'GET_SESSION_TOKEN_FROM_LOCAL_STORAGE';
export const CHANGED_PHONE_NUMBER_TEXT = 'CHANGED_PHONE_NUMBER_TEXT';
export const CHANGED_VERIFICATION_CODE_TEXT = 'CHANGED_VERIFICATION_CODE_TEXT';
export const REQUEST_VERIFICATION_CODE = 'REQUEST_VERIFICATION_CODE';
export const VERIFY_PHONE_NUMBER = 'VERIFY_PHONE_NUMBER';
export const HERO_MODE = 'HERO_MODE';

// EVENTS
export const FETCHING_EVENTS = 'FETCHING_EVENTS';
export const NEW_EVENT_CREATED = 'NEW_EVENT_CREATED';
export const GET_EVENTS = 'GET_EVENTS';
export const GET_EVENT_GUEST_LIST = 'GET_EVENT_GUEST_LIST';
export const CLEAR_EVENT_GUEST_LIST = 'CLEAR_EVENT_GUEST_LIST';
export const CHANGE_EVENTS_FILTER = 'CHANGE_EVENTS_FILTER';
export const GET_EVENT_COMMENTS = 'GET_EVENT_COMMENTS';
export const CLEAR_EVENT_COMMENTS = 'CLEAR_EVENT_COMMENTS';

// FRIENDS
export const GET_FRIENDS_LIST = 'GET_FRIENDS_LIST';
export const SET_FRIENDS_SEGMENT = 'SET_FRIENDS_SEGMENT';
export const RESPOND_TO_FRIEND_REQUEST = 'RESPOND_TO_FRIEND_REQUEST';

// USERS
export const GET_LOGGED_IN_USER_INFO = 'GET_LOGGED_IN_USER_INFO';
export const OPEN_EDIT_USER_INFO_MODAL = 'OPEN_EDIT_USER_INFO_MODAL';
export const CLOSE_EDIT_USER_INFO_MODAL = 'CLOSE_EDIT_USER_INFO_MODAL';
export const CHANGED_USERNAME_TEXT = 'CHANGED_USERNAME_TEXT';
export const CHANGED_DISPLAY_NAME_TEXT = 'CHANGED_DISPLAY_NAME_TEXT';
export const SEND_APP_FEEDBACK = 'SEND_APP_FEEDBACK';

// ALEXA 
export const ALEXA_SYNC_CODE = 'ALEXA_SYNC_CODE';
export const ALEXA_SYNC_CONFIRM = 'ALEXA_SYNC_CONFIRM';
export const ALEXA_CONNECTED = 'ALEXA_CONNECTED';
export const ALEXA_CONNECTION_DELETED = 'ALEXA_CONNECTION_DELETED';

// NOTIFICATIONS
export const FETCHING_NOTIFICATIONS = 'FETCHING_NOTIFICATIONS';
export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';

// SEARCH 
export const UPDATED_SEARCH_SUGGESTIONS = 'UPDATED_SEARCH_SUGGESTIONS';